config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources "theaters" do
    resources "theater_movies"
    resources "auditoriums"
  end
  resources "movies"
  resources "auditoriums"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auditorium.rb
class Auditorium < ApplicationRecord
  self.table_name = 'auditoriums'
  validates :name, presence: true, length: {maximum: 15}
  validates :capacity, presence: true, inclusion: {:in => 32..500}
  belongs_to :theater
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :year, presence: true, numericality: {greater_than_or_equal_to: 1900, less_than_or_equal_to: 2019}
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :genre, presence: true, length: { maximum: 15 }
  validates :duration, presence: true, numericality: { greater_than_or_equal_to: 60, less_than_or_equal_to: 360}

  has_many :theater_movies
  has_many :movies, through: :theater_movies
end

app/models/theater.rb
class Theater < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :address, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 30}
  validates :phone_number, presence: true, length: {minimum: 6}

  has_many :theater_movies, dependent: :delete_all
  has_many :auditoriums, dependent: :delete_all
  has_many :movies, through: :theater_movies

  accepts_nested_attributes_for :theater_movies, allow_destroy: true
  accepts_nested_attributes_for :auditoriums, allow_destroy: true
end

app/models/theater_movie.rb
class TheaterMovie < ApplicationRecord
  belongs_to :theater
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auditoriums_controller.rb
class AuditoriumsController < ApplicationController
  before_action :set_theater, only: [:index, :create, :update]

  def index
    @auditoriums = Auditorium.where("theater_id='#{@theater.id}'")
  end

  def new
    @auditorium = Auditorium.new
  end

  def create
    attributes = {auditoriums_attributes: [auditorium_params]}
    @theater.assign_attributes(attributes)
    return redirect_to theater_auditoriums_path(@theater.id) if @theater.save

    @auditorium = Auditorium.new(auditorium_params)
    flash[:error] = @theater.errors.full_messages.to_sentence
    render 'new'
  end

  def edit
    @auditorium = Auditorium.find(params[:id])
  end

  def update
    @auditorium = Auditorium.find(params[:id])
    return redirect_to theater_auditoriums_path(params[:theater_id]) if (@auditorium.update_attributes(auditorium_params))

    flash[:error] = @auditorium.errors.full_messages.to_sentence
    render 'edit'
  end

  def destroy
    @auditorium = Auditorium.find(params[:id])
    @auditorium.destroy
    return redirect_to theater_auditoriums_path
  end

  private

  def set_theater
    @theater = Theater.find(params[:theater_id])
  end

  def auditorium_params
    params.require(:auditorium).permit(:name, :capacity, :theater_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    return redirect_to(movies_path) if (@movie.save)
    render('new')
  end

  def edit

  end

  def update
    return redirect_to movies_path if (@movie.update_attributes(movie_params))
    render('edit')
  end

  def destroy
    @movie.destroy
    return redirect_to movies_path
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:name, :year, :rating, :genre, :duration)
  end
end

app/controllers/theater_movies_controller.rb
class TheaterMoviesController < ApplicationController
  before_action :set_theater, only: [:index, :new, :create]

  def index
    @theaterMovies = @theater.theater_movies
  end

  def new
    @theaterMovies = TheaterMovie.new(theater_id: @theater.id)
    @movie = Movie.all
  end

  def create
    attributes = {theater_movies_attributes: [{movie_id: params[:movie_id]}]}
    @theater.assign_attributes(attributes)
    return redirect_to theater_theater_movies_path if (@theater.save)

    render theater_theater_movie_path
  end

  def destroy
    @theaterMovies = TheaterMovie.find(params[:id])
    @theaterMovies.destroy
    return redirect_to theater_theater_movies_path
  end

  def set_theater
    @theater = Theater.find(params[:theater_id])
  end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: [:show, :edit, :update, :destroy]

  def index
    @theaters = Theater.all
  end

  def new
    @theater = Theater.new
  end

  def create
    @theater = Theater.new(theater_params)
    return redirect_to (theaters_path) if @theater.save
    render('new')
  end

  def show

  end

  def edit

  end

  def update
    return redirect_to theaters_path if (@theater.update_attributes(theater_params))
    render('edit')
  end

  def destroy
    @theater.destroy
    redirect_to (theaters_path)
  end

  private
  def set_theater
    @theater = Theater.find(params[:id])
  end

  def theater_params
    params.require(:theater).permit(:name, :email, :address, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditoriums_helper.rb
module AuditoriumsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/theater_movies_helper.rb
module TheaterMoviesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/auditoriums/edit.html.erb
<h1>Edit <%= @auditorium.name %></h1>
<%= link_to "<<Back to the list", theater_auditoriums_path %>

<%= form_for @auditorium, url: theater_auditorium_path, method: :patch  do |a| %>
  <% if flash[:error] %>
    <div>
      <%= flash[:error] %>
    </div>
  <% end %>
  <p>
    <%= a.text_field :name %>
  </p>
  <p>
    <%= a.text_field :capacity %>
  </p>
  <p>
    <%= a.submit value="Edit Auditorium" %>
  </p>
<% end %>

app/views/auditoriums/index.html.erb
<h1><%= @theater.name %>'s auditoriums</h1>
<%= link_to "<<Back to list", theater_path(@theater) %>
<hr>
<table>
  <tr>
    <th>Name</th>
    <th>Capacity</th>
  </tr>
  <% @auditoriums.each do |auditorium| %>
  <tr>
    <td><%= auditorium.name %></td>
    <td><%= auditorium.capacity %></td>
    <!-- <td><%#= link_to "Show", auditorium_path(auditorium) %></td> -->
    <td><%= link_to "Edit", edit_theater_auditorium_path(@theater.id, auditorium.id) %></td>
    <td><%= link_to "Delete", theater_auditorium_path(@theater.id, auditorium.id), method: :delete, data: {confirm: "Are you sure?"}%></td>
  </tr>
  <% end %>
</table>
<hr>
<%= link_to "Add New Auditorium", new_theater_auditorium_path %>

app/views/auditoriums/new.html.erb
<h1>Adding new auditorium</h1>
<% if flash[:error] %>
  <div>
    <%= flash[:error] %>
  </div>
<% end %>

<%= link_to "<<Back to list", theater_auditoriums_path %>

<%= form_for(@auditorium, url: theater_auditoriums_path, method: :post) do |a| %>
  <p>
    <%= a.text_field :name %>
  </p>
  <p>
    <%= a.text_field :capacity %>
  </p>
  <p>
    <%= a.submit value="Add Auditorium" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Editing new movie to the list</h1>

<%= link_to("<<Back to the list", movies_path) %>

<%= form_for(@movie) do |m| %>
  <% if @movie.errors.any? %>
    <% @movie.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>
  <p>
    Name
    <%= m.text_field :name %>
  </p>
  <p>
    Year
    <%= m.text_field :year %>
  </p>
  <p>
  <p>
    Rating
    <%= m.text_field :rating %>
  </p>
  <p>
    Genre
    <%= m.text_field :genre %>
  </p>
  <p>
    Duration
    <%= m.text_field :duration %>
  </p>
  <p>
    <%= m.submit value="Update Movie" %>
  </p>
<% end %>

app/views/movies/index.html.erb
<h1>List of Movies</h1>
<hr>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Rating</th>
    <th>Genre</th>
    <th>Duration(Mins)</th>
  </tr>
  </thead>
  <tbody>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.name %></td>
      <td><%= movie.year %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.genre %></td>
      <td><%= movie.duration %></td>
      <td>
        <%= link_to("Edit", edit_movie_path(movie.id)) %>
        <%= link_to("Delete", movie_path(movie.id), method: :delete, data: {confirm: "Are you sure"}) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<hr>
<%= link_to("Add New Movie", new_movie_path) %>

app/views/movies/new.html.erb
<h1>Adding new movie to the list</h1>

<%= link_to("<<Back to the list", movies_path) %>

<%= form_for(@movie) do |m| %>
  <% if @movie.errors.any? %>
    <% @movie.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>
  <p>
    Name
    <%= m.text_field :name %>
  </p>
  <p>
    Year
    <%= m.text_field :year %>
  </p>
  <p>
    Rating
    <%= m.text_field :rating %>
  </p>
  <p>
    Genre
    <%= m.text_field :genre %>
  </p>
  <p>
    Duration
    <%= m.text_field :duration %>
  </p>
  <p>
    <%= m.submit value="Add Movie" %>
  </p>
<% end %>

app/views/theater_movies/index.html.erb
<h1>List of all movies</h1>
<%= link_to "<<Back to list", theater_path(@theater) %>
<hr>
<table style="text-align: center">
  <thead>
  <th>Name</th>
  <th>Year</th>
  <th>Rating</th>
  <th>Genre</th>
  <th>Duration(Mins)</th>
  </thead>
  <tbody>
  <% @theaterMovies.each do |theaterMovie| %>
    <tr>
      <td><%= link_to(theaterMovie.movie.name, "#") %></td>
      <td><%= theaterMovie.movie.year %></td>
      <td><%= theaterMovie.movie.rating %></td>
      <td><%= theaterMovie.movie.genre %></td>
      <td><%= theaterMovie.movie.duration %></td>
      <td>
        <%= form_for [@theater, theaterMovie], method: :delete, data: {confirm: "Are You Sure?"} do %>
          <%= hidden_field_tag(:theater_id, @theater.id) %>
          <%= submit_tag("Delete") %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<hr>
<%= link_to "Add New Movie", new_theater_theater_movie_path(@theater.id) %>

app/views/theater_movies/new.html.erb
<%= form_for @theaterMovies, url: theater_theater_movies_path(@theater.id), method: :post do %>
  <%= select_tag 'movie_id', options_for_select(@movie.collect{ |u| [u.name, u.id] })%>
  <%= submit_tag value="submit" %>
<% end %>

app/views/theaters/edit.html.erb
<h1>Edit <%= @theater.name %></h1>
<%= link_to("<<Back to the list", theaters_path) %>

<%= form_for(@theater) do |t| %>

  <% if @theater.errors.any? %>
    <% @theater.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <p>
    Name: <br>
    <%= t.text_field :name %>
  </p>
  <p>
    Email:
    <%= t.text_field :email %>
  </p>
  <p>
    Address:
    <%= t.text_field :address %>
  </p>
  <p>
    Phone Number:
    <%= t.text_field :phone_number %>
  </p>
  <p>
  <p>
    <%= t.submit %>
  </p>
<% end %>

app/views/theaters/index.html.erb
<h1>List of all Movie Theaters</h1>
<hr>
<table style="text-align: center">
  <tr>
    <th>Movie Theaters</th>
  </tr>
  <% @theaters.each do |theater| %>
    <tr>
      <td><%= theater.name %></td>
      <td>
        <%= link_to("Show", theater_path(theater.id)) %>
        <%= link_to("Edit", edit_theater_path(theater.id)) %>
        <%= link_to("Delete", theater_path(theater.id), method: :delete, data: {confirm: "Are You Sure?"}) %>
      </td>
    </tr>
  <% end %>
</table>
<hr>
<%= link_to("Add New Theatre", new_theater_path) %>

app/views/theaters/new.html.erb
<h1>Add New Movie Theatre</h1>

<%= link_to("<<Back to the list", theaters_path) %>
<hr>

<%= form_for(@theater) do |t| %>

  <% if @theater.errors.any? %>
    <% @theater.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <p>
    Name:
    <%= t.text_field :name %>
  </p>
  <p>
    Email:
    <%= t.text_field :email %>
  </p>
  <p>
    Address:
    <%= t.text_field :address %>
  </p>
  <p>
    Phone Number:
    <%= t.text_field :phone_number %>
  </p>
  <p>
    <%= t.submit value="Add Theater" %>
  </p>
<% end %>

app/views/theaters/show.html.erb
<h1>Displaying <%= @theater.name %></h1>
<%= link_to("<<Back to list", theaters_path) %>
<hr>

<table style="text-align: center">
  <thead>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Phone Number</th>
  </thead>
  <tbody>
      <tr>
        <td><%= @theater.name %></td>
        <td><%= @theater.email %></td>
        <td><%= @theater.address %></td>
        <td><%= @theater.phone_number %></td>
      </tr>
  </tbody>
</table>
<hr>
<form>
<%= link_to "Movies", theater_theater_movies_path(@theater.id) %>
<%= link_to "Auditorium", theater_auditoriums_path(@theater.id) %>
<%= link_to "Sessions", "#" %>
</form>